/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat.app.form;

import chat.app.component.Item_people;
import chat.app.swing.Scrollbar;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author MIR HAMZA
 */
public class Menu_Left extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    public Menu_Left() {
        initComponents();
        init();
    }
    public void init(){
        sp.setVerticalScrollBar(new Scrollbar());
       
        MenuList.setLayout(new MigLayout("fillx","0[]0","0[]0"));
        showpeople();
    }
    private void showpeople(){
        MenuList.removeAll();
        for (int i = 0; i < 20; i++) {
            MenuList.add(new Item_people("People "+i),"Wrap");
        }
        MenuList.repaint();
        MenuList.revalidate();
    }
    private void showgroup(){
                MenuList.removeAll();
        for (int i = 0; i < 5; i++) {
            MenuList.add(new Item_people("Group "+i),"Wrap");
        }
                MenuList.repaint();
        MenuList.revalidate();
    }
    private void showbox(){
                MenuList.removeAll();
        for (int i = 0; i < 2; i++) {
            MenuList.add(new Item_people("Box "+i),"Wrap");
        }
                MenuList.repaint();
        MenuList.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menumsg = new chat.app.component.MenuButton();
        menugroup = new chat.app.component.MenuButton();
        menubox = new chat.app.component.MenuButton();
        sp = new javax.swing.JScrollPane();
        MenuList = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(242, 242, 242));

        menu.setBackground(new java.awt.Color(229, 229, 229));
        menu.setOpaque(true);
        menu.setLayout(new java.awt.GridLayout(1, 3));

        menumsg.setIconselected(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/message_selected.png"))); // NOI18N
        menumsg.setIconsimple(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/message.png"))); // NOI18N
        menumsg.setSelected(true);
        menumsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumsgActionPerformed(evt);
            }
        });
        menu.add(menumsg);

        menugroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/group.png"))); // NOI18N
        menugroup.setIconselected(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/group_selected.png"))); // NOI18N
        menugroup.setIconsimple(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/group.png"))); // NOI18N
        menugroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menugroupActionPerformed(evt);
            }
        });
        menu.add(menugroup);

        menubox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/box.png"))); // NOI18N
        menubox.setIconselected(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/box_selected.png"))); // NOI18N
        menubox.setIconsimple(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/box.png"))); // NOI18N
        menubox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuboxActionPerformed(evt);
            }
        });
        menu.add(menubox);

        sp.setBackground(new java.awt.Color(242, 242, 242));
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        MenuList.setBackground(new java.awt.Color(242, 242, 242));
        MenuList.setOpaque(true);

        javax.swing.GroupLayout MenuListLayout = new javax.swing.GroupLayout(MenuList);
        MenuList.setLayout(MenuListLayout);
        MenuListLayout.setHorizontalGroup(
            MenuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuListLayout.setVerticalGroup(
            MenuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        sp.setViewportView(MenuList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menumsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumsgActionPerformed
        // TODO add your handling code here:
        if(!menumsg.isSelected()){
        menumsg.setSelected(true);
        menugroup.setSelected(false);
        menubox.setSelected(false);  
        showpeople();
        }
        
        
    }//GEN-LAST:event_menumsgActionPerformed

    private void menugroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menugroupActionPerformed
        // TODO add your handling code here:
        if(!menugroup.isSelected()){
        menumsg.setSelected(false);
        menugroup.setSelected(true);
        menubox.setSelected(false);
        showgroup();
        }
        
    }//GEN-LAST:event_menugroupActionPerformed

    private void menuboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuboxActionPerformed
        // TODO add your handling code here:
        if(!menubox.isSelected()){
        menumsg.setSelected(false);
        menugroup.setSelected(false);
        menubox.setSelected(true);
        showbox();
        }
    }//GEN-LAST:event_menuboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane MenuList;
    private javax.swing.JLayeredPane menu;
    private chat.app.component.MenuButton menubox;
    private chat.app.component.MenuButton menugroup;
    private chat.app.component.MenuButton menumsg;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
