/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat.app.component;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author MIR HAMZA
 */
public class chat_Left_With_Profile extends javax.swing.JLayeredPane {

    /**
     * Creates new form chat_Left
     */
    public chat_Left_With_Profile() {
        initComponents();
        txt.setBackground(new Color(242,242,242));
        
    }
    public void setUserProfile(String user){
        txt.setUserProfile(user);
    }
    public void setImage(Icon img){
        image.setImage(img);
    }
    public void setText(String text){
        if(text.equals("")){
            txt.hidetext();
        }
        else{
            txt.setText(text);
        }
//        txt.setTime("10:30 PM");
//        txt.sendSuccess();
        
    }
    public void setImage(Icon... image){
        txt.setImage(false, image);
    }
    
    public void setImage(String... image){
        txt.setImage(false, image);
    }
    
    public void setTime(){
        txt.setTime("10:30 PM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        image = new chat.app.swing.ImageAvatar();
        txt = new chat.app.component.chat_item();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        image.setBorderSize(0);
        image.setImage(new javax.swing.ImageIcon(getClass().getResource("/chat/app/icon/testing/dog.jpg"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(31, 31));
        image.setMinimumSize(new java.awt.Dimension(31, 31));
        image.setPreferredSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chat.app.swing.ImageAvatar image;
    private javax.swing.JLayeredPane jLayeredPane1;
    private chat.app.component.chat_item txt;
    // End of variables declaration//GEN-END:variables
}
